### ISSUE TITLE
Block align encrypted bytes in non super frame as well for consistency

### ISSUE THREAD

**Issue by kqyang** [webmproject/vp9-dash#34]
> When encrypting superframes, the uncompressed headers of the displayed frame,
the uncompressed headers for all ALTREF frames, and the the superframe header
must be clear. The encrypted bytes of each frame within the superframe must be
block aligned so that the counter state can be computed for each frame within
the superframe. Block alignment is achieved by adjusting the size of the
unencrypted bytes that precede the encrypted bytes for that frame.

Right now the specification only requires encrypted bytes of the frames within the superframe to be block aligned. I think we should require encrypted bytes within non superframes to be aligned as well, for consistency.

**Comment by tinskip** [comment]
Addressed by moving some text around in PR #67.
